local SCM = select(2, ...)

SCM.Defaults = {}

SCM.DefaultDB = {
	global = {
		globalAnchorConfig = {
			[1] = {
				anchor = { "CENTER", "UIParent", "CENTER", 0, -360 },
				rowConfig = {
					[1] = {
						size = 40,
						limit = 8,
					},
				},
			},
		},
		globalCustomConfig = {
			spellConfig = {},
			itemConfig = {},
			slotConfig = {},
			timerConfig = {},
		},
	},
	profile = {
		options = {
			anchorUUFRoles = {
				["HEALER"] = false,
				["DAMAGER"] = true,
				["TANK"] = true,
			},
			anchorElvUIRoles = {
				["HEALER"] = false,
				["DAMAGER"] = true,
				["TANK"] = true,
			},
			showAnchorHighlight = true,
			hideWhileMounted = false,
			debug = false,
			enableSkinning = true,
			enableCustomIcons = true,
			simulateAuras = true,
			chargeFont = "Expressway",
			chargeFontSize = 22,
			chargePoint = "CENTER",
			chargeRelativePoint = "BOTTOMRIGHT",
			chargeXOffset = -8,
			chargeYOffset = 10,
			changeCooldownFont = true,
			cooldownFont = "Expressway",
			cooldownFontSize = 0.6,
			useCustomGlow = false,
			glowType = "Proc",
			borderSize = 1,
			anchorUUF = false,
			anchorElvUI = false,
			borderColor = { r = 0, g = 0, b = 0, a = 1 },
			adjustResourceWidth = true,
			pandemicGlowOption = "keepPandemicGlow",
			recolorActiveSwipe = false,
			disableRegularIconActiveSwipe = false,
			activeSwipeColor = { 0, 0, 0, 0.7 },
			normalSwipeColor = { 0.1, 0.1, 0.1, 0.7 },
			castbarXOffset = 0,
			castbarYOffset = 25,
			glowTypeOptions = {
				["Proc"] = {
					glowColor = { 0.95, 0.95, 0.32, 1 },
				},
				["Pixel"] = {
					numLines = 8,
					frequency = 0.25,
					length = 2,
					thickness = 2,
					glowColor = { 0.95, 0.95, 0.32, 1 },
				},
				["Autocast"] = {
					startAnim = true,
					numParticles = 4,
					frequency = 0.125,
					scale = 1,
					glowColor = { 0.95, 0.95, 0.32, 1 },
				},
			},
			buffBarOptions = {
				barTexture = "Solid",
				borderSize = 2,
				borderColor = {r = 0, g = 0, b = 0, a = 1},
				backgroundColor = {r = 0.2, g = 0.2, b = 0.2, a = 0.5},
				foregroundColor = {r = 0.5, g = 0.5, b = 1, a = 1},
				font = "Expressway",
				fontSize = 15,
			},
			resourceBars = {
				"PrimaryResourceBar",
				"SecondaryResourceBar",
			},
			resourceBar = {
				enabled = true,
				hideWhileMounted = false,
				anchorFrame = "ANCHOR:1",
				point = "BOTTOM",
				relativePoint = "TOP",
				xOffset = 0,
				yOffset = 0,
				spacing = -1,
				growDirection = "UP",
				useFrequentPowerUpdates = false,
				maelstromOverflowColor = { r = 0.25, g = 0.70, b = 1.00 },
				powerTypeColorOverrides = {
					MANA = { enabled = false, color = { r = 0.00, g = 0.45, b = 1.00 } },
					RAGE = { enabled = false, color = { r = 1.00, g = 0.15, b = 0.15 } },
					FOCUS = { enabled = false, color = { r = 1.00, g = 0.50, b = 0.25 } },
					ENERGY = { enabled = false, color = { r = 1.00, g = 0.85, b = 0.10 } },
					COMBO_POINTS = { enabled = false, color = { r = 1.00, g = 0.96, b = 0.41 } },
					RUNES = { enabled = false, color = { r = 0.55, g = 0.55, b = 0.55 } },
					RUNIC_POWER = { enabled = false, color = { r = 0.00, g = 0.82, b = 1.00 } },
					SOUL_SHARDS = { enabled = false, color = { r = 0.50, g = 0.32, b = 0.55 } },
					LUNAR_POWER = { enabled = false, color = { r = 0.30, g = 0.52, b = 0.90 } },
					HOLY_POWER = { enabled = false, color = { r = 0.95, g = 0.90, b = 0.60 } },
					MAELSTROM = { enabled = false, color = { r = 0.00, g = 0.50, b = 1.00 } },
					CHI = { enabled = false, color = { r = 0.71, g = 1.00, b = 0.92 } },
					INSANITY = { enabled = false, color = { r = 0.40, g = 0.00, b = 0.80 } },
					ARCANE_CHARGES = { enabled = false, color = { r = 0.10, g = 0.10, b = 0.98 } },
					FURY = { enabled = false, color = { r = 0.79, g = 0.26, b = 0.99 } },
					PAIN = { enabled = false, color = { r = 1.00, g = 0.61, b = 0.00 } },
					ESSENCE = { enabled = false, color = { r = 0.32, g = 0.84, b = 0.90 } },
					STAGGER = { enabled = false, color = { r = 0.52, g = 1.00, b = 0.52 } },
					MAELSTROM_WEAPON = { enabled = false, color = { r = 0.00, g = 0.50, b = 1.00 } },
					SOUL_FRAGMENTS = { enabled = false, color = { r = 0.35, g = 0.25, b = 0.73 } },
					SOUL_FRAGMENTS_VENGEANCE = { enabled = false, color = { r = 0.35, g = 0.25, b = 0.73 } },
					TIP_OF_THE_SPEAR = { enabled = false, color = { r = 1.00, g = 0.82, b = 0.20 } },
				},
				primaryBar = {
					enabled = true,
					matchAnchorWidth = true,
					width = 200,
					hideManaRoles = {
						["TANK"] = true,
						["DAMAGER"] = true,
						["HEALER"] = true,
					},
					font = "Expressway",
					fontSize = 21,
					textXOffset = 0,
					textYOffset = -1,
					textOutline = "OUTLINE",
					texture = "Solid",
					useBackgroundTexture = true,
					backgroundTexture = "Solid",
					backgroundColor = { r = 0, g = 0, b = 0, a = 0.35 },
					showTicks = true,
					tickWidth = 2,
					tickColor = { r = 0, g = 0, b = 0, a = 1 },
					showBorder = true,
					backdropSize = 2,
					backdropColor = { r = 0, g = 0, b = 0, a = 1 },
					height = 20,
					showValues = true,
				},
				secondaryBar = {
					enabled = true,
					matchAnchorWidth = true,
					width = 200,
					hideManaRoles = {
						["TANK"] = true,
						["DAMAGER"] = true,
						["HEALER"] = true,
					},
					font = "Expressway",
					fontSize = 27,
					textXOffset = 0,
					textYOffset = 5,
					textOutline = "OUTLINE",
					texture = "Solid",
					useBackgroundTexture = true,
					backgroundTexture = "Solid",
					backgroundColor = { r = 0, g = 0, b = 0, a = 0.35 },
					showTicks = true,
					tickWidth = 2,
					tickColor = { r = 0, g = 0, b = 0, a = 1 },
					showBorder = true,
					backdropSize = 2,
					backdropColor = { r = 0, g = 0, b = 0, a = 1 },
					height = 20,
					showValues = true,
				},
			},
			castBar = {
				enable = true,
				width = 270,
				height = 24,
				texture = "Solid",
				font = "Expressway",
				fontSize = 12,
				fontOutline = "OUTLINE",
				matchParentWidth = true,
				fgColor = { r = 0.5, g = 0.5, b = 1, a = 1 },
				bgColor = { r = 0, g = 0, b = 0, a = 0.8 },
				interruptColor = { r = 1, g = 0.25, b = 0.25, a = 1 },
				borderColor = { r = 0, g = 0, b = 0, a = 1 },
				anchors = { "BOTTOM", "SCM_SecondaryResourceBar,SCM_PrimaryResourceBar,ANCHOR:1", "TOP", 0, 0 },
				icon = {
					enable = true,
					matchBarHeight = true,
					size = 24,
					zoom = 0.08,
					position = "LEFT",
				},
				spellName = {
					enable = true,
					anchors = { "LEFT", "LEFT", 3, 0 },
				},
				castDuration = {
					enable = true,
					anchors = { "RIGHT", "RIGHT", -3, 0 },
				},
			},
			testSetting = {
				[193063] = false,
			},
		},
	},
}

SCM.DB = {
	classes = {},

	defaultAnchorConfig = {
		[1] = {
			anchor = { "CENTER", "UIParent", "CENTER", 0, -285 },
			rowConfig = {
				[1] = {
					size = 47,
					limit = 8,
				},
			},
		},
		[2] = {
			anchor = { "TOP", "ANCHOR:1", "BOTTOM", 0, 1 },
			rowConfig = {
				[1] = {
					size = 41,
					limit = 8,
				},
			},
		},
		[3] = {
			anchor = { "TOP", "ANCHOR:2", "BOTTOM", 0, 1 },
			rowConfig = {
				[1] = {
					size = 40,
					limit = 8,
				},
			},
		},
	},
}

SCM.DefaultClassConfig = {
	spellConfig = {},
	anchorConfig = {},
	buffBarsAnchorConfig = {},
	itemConfig = {},
	customConfig = {},
}

SCM.Defaults.GlobalSettingsTabs = {
	{ value = "General", text = "General" },
	{ value = "Glow", text = "Glow" },
	{ value = "BuffBar", text = "Buff Bars" },
}
